# 운영환경 설정
# application-prod.properties

# 데이터베이스 연결 설정
spring.datasource.url=ENC(FOzk8EI1sAkX39rSN8w//udHv6uFxClTpQpScWh/M8XOWLnYh48wLQhzhceBpj9iYFOD+mP/YvY=)
spring.datasource.username=ENC(Fd38nA8wFfyH4/l2LrdkqQ==)
spring.datasource.password=ENC(n/IEbZt6HIjaGZfS7+T0XlX9uK6A2ZZj)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# 서버 설정
server.port=8080

# 로깅 설정
logging.level.root=WARN

# 파일 저장 경로 설정 (이미지와 문서 분리)
file.upload-dir.images=ENC(Ptz2Sg6gMoe3GooPEMt/vmNv+HVh1bFYQRmV/hIfNV6ygJkdzaCpiQ==)
file.upload-dir.documents=ENC(MEVH97OTtcthUnse1+xKCXEKU2v0NrZDOn/hxxvst+//1c5363vk3gJUP03A8G/0)

# 파일 업로드 제한 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 주의: 운영 환경에서는 반드시 JASYPT_ENCRYPTOR_PASSWORD 환경 변수를 설정해야 합니다
# spring.datasource.username은 암호화되어 있습니다
# spring.datasource.password은 암호화되어 있습니다
